### ISSUE TITLE
Adding giftcard with existing ID gives cryptic error

### ISSUE THREAD

**Issue by jettro** [AxonIQ/giftcard-demo#16]
There is an exception when creating a Giftcard with an existing ID. The exception is a technical exception that a normal user would not understand.

OUT_OF_RANGE: AXONIQ-2000 Invalid Sequence number 0 for aggregate Coen-1, expected 3

I guess this means we do not support creating a Giftcard with an existing ID. To show exception handling could be good to show this the right way as well

**Comment by smcvb** [comment]
Agreed there, @jettro. 
I, however, feel that (1) either Axon Server should provide a more specific exception (just like the RDBMS/Mongo EventStorageEngine in Framework) or (2) Framework should translate the exception to a more specific problem.
Nonetheless, for the demo's sake, I am not catching the exception and rewording it to something more reasonable.
