### ISSUE TITLE
Add load generation module

### ISSUE THREAD

**Issue by abuijze** [AxonIQ/giftcard-demo#3]
The load generation module should have a command handler that takes a single command, which causes it to start a load test cycle using the parameters of the command.

The module should have a UI component that sends one or more of these commands to the modules that have been deployed.

Commands generated by the load test module should have a lower priority, so that commands through interactive interfaces (such as gc-gui) are handled first.

**Comment by svanschooten** [comment]
This is exactly what I was looking for! Any clue on the timeline/roadmap?

**Comment by smcvb** [comment]
The [`BulkIssuer`](https://github.com/AxonIQ/giftcard-demo/blob/master/src/main/java/io/axoniq/demo/giftcard/gui/BulkIssuer.java) that's part of this project fulfills this use case right now.
As such, I feel comfortable closing this issue as resolved.
