### ISSUE TITLE
Measure and report message throughput in components

### ISSUE THREAD

**Issue by abuijze** [AxonIQ/giftcard-demo#5]
All the components should report performance metrics they observe. The metrics can be exposed using HTTP endpoints (via Spring Boot Actuator, for example) and retrieved by the Load Test GUI on regular intervals.

**Comment by smcvb** [comment]
This project uses the `axon-micrometer` module in combination with `spring-boot-starter-actuator` to achieve just that.
As such, I feel comfortable closing this issue as 'resolved.'
Feel free to keep commenting if something's missed.
